CREATE TABLE PARCEIROS(ID INT PRIMARY KEY,
   TRADING_NAME VARCHAR (255),
   OWNER_NAME VARCHAR (255),
   DOCUMENT VARCHAR (255),
   COVERAGE_AREA VARCHAR (255),
   ADDRESS_COORDINATES VARCHAR (255));
